version: '3.9'
name: roundout
services:
  api:
    build:
      context: .
      target: development
      dockerfile: ./dockerfile
    container_name: 'roundout_api'
    env_file: .env.development
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
      - './tsconfig.json:/app/tsconfig.json'
      - './package.json:/app/package.json'

    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      - DATABASE_URL=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=roundout_db
    container_name: roundout_postgres
    ports:
      - '5432:5432'
