# Generated by Django 5.0.7 on 2024-09-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='athletes',
            field=models.ManyToManyField(to='users.athlete', verbose_name='athletes'),
        ),
    ]
