# Generated by Django 5.0.7 on 2024-09-09 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('address', models.CharField(max_length=255, verbose_name='endereço')),
                ('capacity', models.IntegerField(verbose_name='capacidade')),
            ],
            options={
                'verbose_name': 'instalação',
                'verbose_name_plural': 'instalações',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=10, verbose_name='nome da mesa')),
                ('availability', models.BooleanField(default=True, verbose_name='está disponível?')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='facilities.facility', verbose_name='instalação')),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
            },
        ),
    ]
